#!/bin/bash

# install bash_kernel to Jupyter
python -m bash_kernel.install

# Get PatMAtch and unpack
# Unlike with [circos](https://github.com/fomightez/circos-binder/blob/master/postBuild), 
# cannot get software at time of build because MyBinder.org blocks FTP. Since can't get from
# [FTP server](ftp://ftp.arabidopsis.org/home/tair/Software/Patmatch/) via curl, 
# at time of building image,I added it to repo so it can be access and compiled then.  
#curl -O ftp://ftp.arabidopsis.org/home/tair/Software/Patmatch/patmatch_1.2.tar.gz
tar xvfz patmatch_1.2.tar.gz
rm patmatch_1.2.tar.gz

# Compile PatMatch
cd patmatch_1.2
make