#!/bin/bash

# retrieve notebooks and place correctly in session
rm index.ipynb
git clone https://github.com/fomightez/ptmbr-accompmatz.git
cp ptmbr-accompmatz/index.ipynb .
mv ptmbr-accompmatz/notebooks .
rm -rf ptmbr-accompmatz



# this must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"